### 모든 유저 조회
GET http://localhost:5015/api/users


### 특정 유저 조회 (id가 1인 유저)
GET http://localhost:5015/api/users/cmknj1dhp0000bow1ritwv062
###

### 새 유저 생성
POST http://localhost:5015/api/users
Content-Type: application/json

{
  "email": "tes1t@test.com",
  "name": "홍길동"
}

###

### 유저 수정
PATCH http://localhost:5015/api/users/cmknj1dhp0000bow1ritwv062
Content-Type: application/json

{
  "name": "나이스장"
}

###

### 유저 삭제
DELETE http://localhost:5015/api/users/cmkm2zlp40000esw10nz88ir1

### 중복 이메일로 생성 시도

POST http://localhost:5015/api/users
Content-Type: application/json

{
  "email": "alsisce1234@example.com",
  "name": "테스트2"
}

### 존재하지 않는 사용자 조회
GET http://localhost:5015/api/users/999



### 사용자와 게시글 함께 조회
GET http://localhost:5015/api/users/cmknj1dhp0000bow1ritwv062/posts


### 4. 모든 게시물 조회
GET http://localhost:5015/api/posts

### 5. 게시물 생성
POST http://localhost:5015/api/posts
Content-Type: application/json

{
  "title": "JavaScript 기초",
  "content": "JavaScript는 프로그래밍 언어입니다",
  "published": true,
  "authorId": "cmknj1dhp0000bow1ritwv062" 
}


### 페이지네이션 테스트 1페이지 조회
GET http://localhost:5015/api/posts?page=1&limit=5


### 페이지네이션 2페이지 조회
GET http://localhost:5015/api/posts?page=2&limit=5

### 검색 테스트
GET http://localhost:5015/api/posts/search?q=JavaScript

### 공개 게시글 조회
GET http://localhost:5015/api/posts/published

### 모지 ? 
GET /api/posts?published=true&authorId=1&page=2&limit=5&sortBy=createdAt&order=desc


### 게시글과 댓글 함께 생성
POST http://localhost:5015/api/posts/with-comment
Content-Type: application/json

{
  "authorId": "cmknja5hg000m1cw17pqq20j3",
  "title": "트랜잭션 테스트",
  "content": "게시글 내용",
  "commentContent": "첫 댓글입니다!"
}


### 게시글과 댓글 함께 삭제
DELETE http://localhost:5015/api/posts/cmknjvky600005kw1n5issxm2/with-comments

{
  "message": "게시글과 댓글이 삭제되었습니다.",
  "deletedPost": {
    "id": "cmknjvky600005kw1n5issxm2",
    "title": "Alice의 첫 번째 글"
  },
  "deletedCommentsCount": 1
}

### 여러 게시글 일괄  생성

POST http://localhost:5015/api/posts/batch
Content-Type: application/json

{
  "posts": [
    {
      "title": "배치 게시글 1",
      "content": "내용 1",
      "published": true,
      "authorId": "cmknja5hg000m1cw17pqq20j3"
    },
    {
      "title": "배치 게시글 2",
      "content": "내용 2",
      "published": false,
      "authorId": "cmknja5hg000m1cw17pqq20j3"
    },
    {
      "title": "배치 게시글 3",
      "content": "내용 3",
      "published": true,
      "authorId": "cmknja5hg000m1cw17pqq20j3"
    }
  ]
}

