### 모든 유저 조회
GET http://localhost:5015/api/users


### 특정 유저 조회 (id가 1인 유저)
GET http://localhost:5015/api/users/cmkmozkj60000j8w1zlz2h7cf
###

### 새 유저 생성
POST http://localhost:5015/api/users
Content-Type: application/json

{
  "email": "ew@example.com",
  "name": "테스트1"
}

###

### 유저 수정
PATCH http://localhost:5015/api/users/cmkmozkj60000j8w1zlz2h7cf
Content-Type: application/json

{
  "name": "나이스장"
}

###

### 유저 삭제
DELETE http://localhost:5015/api/users/cmkm2zlp40000esw10nz88ir1

### 중복 이메일로 생성 시도

POST http://localhost:5015/api/users
Content-Type: application/json

{
  "email": "alsisce1234@example.com",
  "name": "테스트2"
}

### 존재하지 않는 사용자 조회
GET http://localhost:5015/api/users/999



### 사용자와 게시글 함께 조회
GET http://localhost:5015/api/users/cmkmozkj80001j8w1eiklnp0k/posts


### 4. 모든 게시물 조회
GET http://localhost:5015/api/posts

### 5. 게시물 생성
POST http://localhost:5015/api/posts
Content-Type: application/json

{
  "title": "제목",
  "content": "내용",
  "authorId": "cmkmozkj90002j8w1jgebrnis" 
}


### 페이지네이션 테스트 1페이지 조회
GET http://localhost:5015/api/posts?page=1&limit=5


### 페이지네이션 2페이지 조회
GET http://localhost:5015/api/posts?page=2&limit=5

### 검색 테스트
GET http://localhost:5015/api/posts/search?q=JavaScript

### 공개 게시글 조회
GET http://localhost:5015/api/posts/published


